# Generated by Django 5.1.4 on 2024-12-14 15:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clube',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeClube', models.CharField(max_length=100)),
                ('divisao', models.CharField(max_length=1)),
                ('cidadeOrigem', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cpf', models.CharField(max_length=11, unique=True)),
                ('dateNasc', models.DateField()),
                ('telefone', models.CharField(max_length=13)),
                ('email', models.EmailField(max_length=100)),
                ('senha', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Jogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('hora', models.TimeField()),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estadio', models.CharField(max_length=100)),
                ('numero_cadeiras', models.IntegerField()),
                ('clubeCasa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mandante', to='compra_ingressos_app.clube')),
                ('clubeFora', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visitante', to='compra_ingressos_app.clube')),
            ],
        ),
        migrations.CreateModel(
            name='RegistroCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataRegistro', models.DateField()),
                ('horaRegistro', models.TimeField()),
                ('precoCompra', models.DecimalField(decimal_places=2, max_digits=10)),
                ('jogoCompra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compra_ingressos_app.jogo')),
            ],
        ),
    ]
