# Generated by Django 5.1.4 on 2024-12-12 17:53

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clube',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeClube', models.CharField(max_length=100)),
                ('divisao', models.CharField(max_length=1)),
                ('cidadeOrigem', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='contaComum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numeroConta', models.IntegerField(unique=True)),
                ('aberturaConta', models.DateField()),
                ('fechamentoConta', models.DateField(null=True)),
                ('situacaoConta', models.IntegerField()),
                ('senhaConta', models.CharField(max_length=30)),
                ('saldoConta', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Jogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clubeCasa', models.CharField(max_length=100)),
                ('clubeFora', models.CharField(max_length=100)),
                ('data', models.DateField()),
                ('hora', models.TimeField()),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estadio', models.CharField(max_length=100)),
                ('numero_cadeiras', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PessoaFisica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomePessoa', models.CharField(max_length=100)),
                ('enderecoPessoa', models.CharField(max_length=300)),
                ('cepPessoa', models.IntegerField()),
                ('telefonePessoa', models.CharField(max_length=100)),
                ('rendaPessoa', models.FloatField()),
                ('situacaoPessoa', models.IntegerField(default=1)),
                ('cpfPessoa', models.CharField(max_length=11, unique=True)),
                ('rgPessoa', models.CharField(max_length=10)),
                ('dataNascimento', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cpf', models.CharField(max_length=11, unique=True)),
                ('dateNasc', models.DateField()),
                ('telefone', models.CharField(max_length=13)),
                ('email', models.CharField(max_length=100)),
                ('senha', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='movimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipoMovimento', models.IntegerField()),
                ('dataMovimento', models.DateTimeField(default=datetime.datetime(2024, 12, 12, 14, 53, 29, 810499))),
                ('valorMovimento', models.FloatField()),
                ('idConta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compra_ingressos_app.contacomum')),
            ],
        ),
        migrations.AddField(
            model_name='contacomum',
            name='idCliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compra_ingressos_app.pessoafisica'),
        ),
    ]
