# Generated by Django 5.1.4 on 2024-12-12 17:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compra_ingressos_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimento',
            name='dataMovimento',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 12, 17, 58, 16, 747743)),
        ),
    ]
