# Generated by Django 5.1.4 on 2024-12-13 19:06

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compra_ingressos_app', '0002_alter_movimento_datamovimento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimento',
            name='dataMovimento',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 13, 19, 6, 50, 410750)),
        ),
        migrations.CreateModel(
            name='RegistroCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataRegistro', models.DateField()),
                ('horaRegistro', models.TimeField()),
                ('precoCompra', models.DecimalField(decimal_places=2, max_digits=10)),
                ('jogoCompra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compra_ingressos_app.jogo')),
            ],
        ),
    ]
