# Generated by Django 5.1.4 on 2024-12-14 13:30

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compra_ingressos_app', '0003_alter_movimento_datamovimento_registrocompra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jogo',
            name='clubeCasa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mandante', to='compra_ingressos_app.clube'),
        ),
        migrations.AlterField(
            model_name='jogo',
            name='clubeFora',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visitante', to='compra_ingressos_app.clube'),
        ),
        migrations.AlterField(
            model_name='movimento',
            name='dataMovimento',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 14, 13, 30, 50, 665742)),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='email',
            field=models.EmailField(max_length=100),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='senha',
            field=models.CharField(max_length=255),
        ),
    ]
