# Generated by Django 5.1.4 on 2024-12-14 13:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compra_ingressos_app', '0004_alter_jogo_clubecasa_alter_jogo_clubefora_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimento',
            name='dataMovimento',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 14, 13, 32, 16, 104961)),
        ),
    ]
